# Generated by Django 6.0.7 on 2026-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_is_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, help_text="System/domain this project covers, e.g. 'Order Management · Payments'", max_length=200),
        ),
    ]
