# Generated by Django 6.0.7 on 2026-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Correlate AI', help_text='Shown in the sidebar, browser tab title, and login page — no logo image, text only.', max_length=100)),
                ('embedding_model_path', models.CharField(blank=True, default='all-MiniLM-L6-v2', help_text='Hugging Face model name (downloaded on first use) or an absolute local folder path to a pre-downloaded sentence-transformers model, for the Generative AI pipeline. Use a local path if this server has no Hugging Face Hub access.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
