# Generated by Django 6.0.7 on 2026-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='embedding_model_path',
            field=models.CharField(blank=True, default='embedding_model', help_text="Path to the sentence-transformers model used by the Generative AI pipeline. Defaults to the 'embedding_model' folder bundled in the project root (works offline, no Hugging Face Hub access needed) — resolved relative to the project folder if it exists there, otherwise treated as an absolute local path or a Hugging Face model id to download on first use.", max_length=300),
        ),
    ]
