# Generated by Django 6.0.7 on 2026-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_embedding_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confidence_cap',
            field=models.PositiveSmallIntegerField(default=97, help_text='Maximum possible confidence score — never a false-sounding 100%'),
        ),
        migrations.AddField(
            model_name='project',
            name='confidence_floor',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minimum possible confidence score — even the weakest real cluster shows at least this'),
        ),
        migrations.AddField(
            model_name='project',
            name='confidence_recency_window_days',
            field=models.PositiveSmallIntegerField(default=90, help_text="A ticket counts as 'recent' if created within this many days of now"),
        ),
        migrations.AddField(
            model_name='project',
            name='confidence_weight_density',
            field=models.FloatField(default=0.35, help_text='How much membership density (how tightly HDBSCAN believes these tickets belong together) counts toward confidence'),
        ),
        migrations.AddField(
            model_name='project',
            name='confidence_weight_recency',
            field=models.FloatField(default=0.25, help_text='How much recent activity counts toward confidence'),
        ),
        migrations.AddField(
            model_name='project',
            name='confidence_weight_size',
            field=models.FloatField(default=0.4, help_text="How much cluster size (relative to this run's largest cluster) counts toward confidence"),
        ),
    ]
