# Generated by Django 6.0.7 on 2026-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_embedding_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='embedding_model_path',
            field=models.CharField(blank=True, default='embedding_model', help_text="Local folder containing a sentence-transformers model, used by Generative AI, Smart Search, Find Similar, Smart Assign, and Possible Duplicates. Either a path relative to the app's root folder (e.g. 'embedding_model') or an absolute local path — never a Hugging Face Hub model id; this app never reaches out to Hugging Face. If the folder doesn't exist, those features show a clear error instead of failing silently. Also editable from the Clustering Settings page.", max_length=300),
        ),
    ]
