# Generated by Django 6.0.7 on 2026-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesettings_embedding_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_currency_symbol',
            field=models.CharField(blank=True, default='$', help_text="Prefix shown before every dollar-impact figure, e.g. '$', '€', '£'", max_length=5),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_per_ticket',
            field=models.FloatField(default=0.0, help_text='Estimated fully-loaded cost to handle one ticket in this project (agent time, tooling, etc.) — 0 hides all dollar-impact figures'),
        ),
    ]
