# Generated by Django 6.0.7 on 2026-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_cost_currency_symbol_project_cost_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='llm_bridge_url',
            field=models.CharField(blank=True, help_text="Base URL of the Copilot HTTP Bridge (BACKLOG Theme A), e.g. 'http://127.0.0.1:3939' or a LAN IP if it's running on a different machine. Blank falls back to the LLM_BRIDGE_URL env var, then to http://127.0.0.1:3939. Also editable from the Clustering Settings page — takes effect immediately, no restart needed.", max_length=300),
        ),
    ]
