# Generated by Django 6.0.7 on 2026-07-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('traditional_ml', 'Traditional ML'), ('generative_ai', 'Generative AI')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('confidence', models.FloatField(default=0.0)),
                ('recurring_count', models.PositiveIntegerField(default=0)),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], default='stable', max_length=10)),
                ('is_problem_candidate', models.BooleanField(default=False)),
                ('is_noise', models.BooleanField(default=False, help_text="True for the catch-all 'unclustered' bucket")),
                ('top_country', models.CharField(blank=True, max_length=100)),
                ('top_application', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.project')),
            ],
            options={
                'ordering': ['-recurring_count'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clustering.cluster')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('cluster', 'ticket')},
            },
        ),
    ]
