# Generated by Django 6.0.7 on 2026-07-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='source_description',
            field=models.CharField(blank=True, help_text="Human-readable description of the dataset scope this run used, e.g. 'All 20,113 tickets' or 'sample_2026.xlsx (2,000 tickets)'", max_length=255),
        ),
    ]
