# Generated by Django 6.0.7 on 2026-07-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0002_cluster_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='trend_reasoning',
            field=models.CharField(blank=True, help_text='Plain-English basis for the trend classification, e.g. counts and date windows compared', max_length=500),
        ),
    ]
