# Generated by Django 6.0.7 on 2026-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0003_cluster_trend_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='top_offering',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
