# Generated by Django 6.0.7 on 2026-07-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0004_cluster_top_offering'),
        ('core', '0005_alter_sitesettings_embedding_model_path'),
        ('tickets', '0004_ticket_assigned_to_ticket_created_by_ticket_offering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(help_text='float32 numpy array, packed via .tobytes()')),
                ('dims', models.PositiveSmallIntegerField()),
                ('model_path', models.CharField(help_text='Which embedding model produced this vector — stale rows are detected by comparing this to the currently configured model', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_embeddings', to='core.project')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='tickets.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='clustering__project_1360c8_idx')],
            },
        ),
    ]
