# Generated by Django 6.0.7 on 2026-07-16 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0005_ticketembedding'),
        ('tickets', '0005_ticket_queue_ticket_queue_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(help_text='Cosine similarity, 0-100')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Duplicate'), ('dismissed', 'Not a Duplicate')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_a', to='tickets.ticket')),
                ('ticket_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_b', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-similarity'],
                'unique_together': {('ticket_a', 'ticket_b')},
            },
        ),
    ]
