# Generated by Django 6.0.7 on 2026-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0006_duplicatecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='granularity',
            field=models.CharField(choices=[('broad', 'Broad'), ('balanced', 'Balanced'), ('fine', 'Fine-grained')], default='balanced', help_text='Which granularity preset produced this run', max_length=10),
        ),
    ]
