# Generated by Django 6.0.7 on 2026-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0007_cluster_granularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='regional_divergence',
            field=models.BooleanField(default=False, help_text="True when a region is rising while the cluster's overall trend isn't — a problem that looks fine in aggregate"),
        ),
        migrations.AddField(
            model_name='cluster',
            name='regional_trends',
            field=models.JSONField(blank=True, default=list, help_text='Per-country trend breakdown, top 5 countries by ticket count: [{country, trend, reasoning, count}, ...]'),
        ),
    ]
