# Generated by Django 6.0.7 on 2026-07-16 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0008_cluster_regional_divergence_cluster_regional_trends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set when this cluster is a drill-down sub-cluster of another cluster, rather than a top-level pipeline result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_clusters', to='clustering.cluster'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='resolution_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='resolution_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cluster',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Either analyst-authored or pasted back from an external AI chat (e.g. Copilot) — see resolution_source'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='resolution_source',
            field=models.CharField(blank=True, choices=[('manual', 'Analyst-authored'), ('copilot_assisted', 'AI-suggested via Copilot')], max_length=20),
        ),
    ]
