# Generated by Django 6.0.7 on 2026-07-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0009_cluster_parent_cluster_resolution_added_at_and_more'),
        ('core', '0005_alter_sitesettings_embedding_model_path'),
        ('tickets', '0006_piifinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('traditional_ml', 'Traditional ML'), ('generative_ai', 'Generative AI')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('confidence', models.FloatField(default=0.0)),
                ('recurring_count', models.PositiveIntegerField(default=0)),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], default='stable', max_length=10)),
                ('trend_reasoning', models.CharField(blank=True, max_length=500)),
                ('is_noise', models.BooleanField(default=False)),
                ('top_country', models.CharField(blank=True, max_length=100)),
                ('top_application', models.CharField(blank=True, max_length=150)),
                ('top_offering', models.CharField(blank=True, max_length=255)),
                ('granularity', models.CharField(choices=[('broad', 'Broad'), ('balanced', 'Balanced'), ('fine', 'Fine-grained')], default='balanced', max_length=10)),
                ('source_description', models.CharField(blank=True, help_text='Which projects/tickets this run covered', max_length=255)),
                ('project_count', models.PositiveSmallIntegerField(default=0, help_text="Distinct projects among this cluster's members — 2 or more means a cross-project intersection")),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-project_count', '-recurring_count'],
            },
        ),
        migrations.CreateModel(
            name='GlobalClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clustering.globalcluster')),
                ('project', models.ForeignKey(help_text='Denormalized from ticket.project — this is the whole point of the model, grouping by it is the main query', on_delete=django.db.models.deletion.CASCADE, related_name='global_cluster_memberships', to='core.project')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_cluster_memberships', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('cluster', 'ticket')},
            },
        ),
    ]
