# Generated by Django 6.0.7 on 2026-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0010_globalcluster_globalclustermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalclustermember',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalclustermember',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalclustermember',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
