# Generated by Django 6.0.7 on 2026-07-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0011_globalclustermember_x_globalclustermember_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcluster',
            name='is_significant_intersection',
            field=models.BooleanField(default=False, help_text="True only when the non-majority project(s) contribute enough tickets (>=3 and >=10% of the cluster) to credibly be a shared incident, not just a coincidental stray ticket. project_count alone (>=2) is too weak a bar for the 'Cross-Project Intersection' badge — a 71/3 split isn't the same claim as a 40/34 split, even though both have project_count=2."),
        ),
    ]
