# Generated by Django 6.0.7 on 2026-07-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0012_globalcluster_is_significant_intersection'),
        ('core', '0005_alter_sitesettings_embedding_model_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('traditional_ml', 'Traditional ML'), ('generative_ai', 'Generative AI')], max_length=20)),
                ('source_fields', models.JSONField(default=list, help_text='Ordered Ticket field names to concatenate into the clustering text, e.g. ["title", "description"]')),
                ('normalize_whitespace', models.BooleanField(default=True, help_text='Collapse tabs/newlines/runs of spaces to one space')),
                ('strip_html', models.BooleanField(default=True, help_text='Strip tags/entities from rich-text exports')),
                ('remove_urls', models.BooleanField(default=True)),
                ('remove_emails', models.BooleanField(default=True)),
                ('strip_boilerplate', models.BooleanField(default=False)),
                ('boilerplate_patterns', models.JSONField(default=list, help_text='Phrases (or, if is_regex, regexes) to strip verbatim, e.g. signature blocks or "This is an automated message..." footers. Each entry: {"pattern": str, "is_regex": bool}')),
                ('normalize_unicode', models.BooleanField(default=False, help_text='Accent/diacritic stripping, e.g. "café" -> "cafe"')),
                ('strip_ticket_id_patterns', models.BooleanField(default=False)),
                ('ticket_id_patterns', models.JSONField(default=list, help_text='Same shape as boilerplate_patterns, e.g. {"pattern": "INC\\\\d{7}", "is_regex": true}')),
                ('lowercase', models.BooleanField(default=True)),
                ('keep_only_text', models.BooleanField(default=False, help_text='Strip everything but letters/whitespace — implies remove_special_characters and remove_numbers')),
                ('remove_special_characters', models.BooleanField(default=True)),
                ('remove_numbers', models.BooleanField(default=True)),
                ('remove_stopwords', models.BooleanField(default=True)),
                ('stopwords_add', models.JSONField(default=list, help_text='Extra words appended to the base English stopword list')),
                ('stopwords_exclude', models.JSONField(default=list, help_text="Words removed from the base list even if present — e.g. keep a normally-generic word that's meaningful in this project's data")),
                ('min_token_length', models.PositiveSmallIntegerField(default=1, help_text='1 = off; e.g. 3 drops tokens under 3 characters')),
                ('enable_stemming', models.BooleanField(default=False, help_text='Collapses inflected forms to a common stem, e.g. "failed"/"failing"/"fails" -> one token')),
                ('min_document_frequency', models.PositiveSmallIntegerField(default=2, help_text='TfidfVectorizer min_df — drop terms appearing in fewer than this many tickets')),
                ('max_document_frequency', models.FloatField(default=0.95, help_text='TfidfVectorizer max_df — drop terms appearing in more than this fraction of tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clustering_settings', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'engine')},
            },
        ),
    ]
