# Generated by Django 6.0.7 on 2026-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0013_clusteringsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='One-line plain-English problem summary — pasted back from an external AI chat (Copilot/Claude/etc.) via the same copy/paste bridge as Resolution. Supplements the mechanical TF-IDF `name`/`keywords` with a sentence a support manager would actually say out loud.', max_length=500),
        ),
        migrations.AddField(
            model_name='cluster',
            name='ai_trend_explanation',
            field=models.CharField(blank=True, help_text="AI-drafted hypothesis for *why* this cluster's trend moved the way it did (e.g. a shared vendor, a recent change) — pasted back via the same bridge. Supplements trend_reasoning, which only states the count/date-window basis for the label, not a cause.", max_length=500),
        ),
    ]
