# Generated by Django 6.0.7 on 2026-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0014_cluster_ai_summary_cluster_ai_trend_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatecandidate',
            name='ai_explanation',
            field=models.CharField(blank=True, help_text='One-sentence explanation of *why* this pair looks like a duplicate beyond the similarity score, generated via the Copilot HTTP Bridge (BACKLOG A.5) — read-only reviewer aid, not saved automatically, never affects status/scoring.', max_length=500),
        ),
    ]
