# Generated by Django 6.0.7 on 2026-07-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0015_duplicatecandidate_ai_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='problem_record_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='problem_record_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cluster',
            name='problem_record_draft',
            field=models.TextField(blank=True, help_text='Formal ITSM-format Problem Record (Title/Description/Business Impact/Root Cause/Proposed Next Steps), generated via the Copilot HTTP Bridge (BACKLOG A.12, user-requested leadership-demo/governance-artifact feature) and reviewed/edited before saving — a distinct, more formal document than resolution_notes, not a replacement for it.'),
        ),
    ]
