# Generated by Django 6.0.7 on 2026-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0016_cluster_problem_record_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='ai_trend_explanation',
            field=models.TextField(blank=True, help_text="AI-drafted hypothesis for *why* this cluster's trend moved the way it did (e.g. a shared vendor, a recent change) — pasted back via the same bridge. Supplements trend_reasoning, which only states the count/date-window basis for the label, not a cause. TextField (was CharField(500)) since the prompt now explicitly asks for a detailed, quote-grounded hypothesis, not one line."),
        ),
        migrations.AlterField(
            model_name='duplicatecandidate',
            name='ai_explanation',
            field=models.TextField(blank=True, help_text="Explanation of *why* this pair looks like a duplicate beyond the similarity score, generated via the Copilot HTTP Bridge (BACKLOG A.5) — read-only reviewer aid, saved directly (unlike A.4's draft-then-review), never affects status/scoring. TextField (was CharField(500)) since the prompt now asks for a quote-grounded explanation, not one bare sentence."),
        ),
    ]
