# Generated by Django 6.0.7 on 2026-07-22 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_sitesettings_embedding_model_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A label for this source, e.g. 'Prod API gateway logs'", max_length=200)),
                ('source_type', models.CharField(choices=[('path', 'Filesystem / network path'), ('upload', 'Uploaded file')], default='path', max_length=10)),
                ('path', models.CharField(blank=True, help_text="Absolute filesystem or network path — required when source_type is 'path'", max_length=1000)),
                ('uploaded_file', models.FileField(blank=True, help_text="Required when source_type is 'upload'", null=True, upload_to='logscan/%Y/%m/')),
                ('trigger_mode', models.CharField(choices=[('on_demand', 'On-demand'), ('scheduled', 'Scheduled'), ('continuous', 'Continuous (tailing)')], default='on_demand', max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='Scheduled/continuous scans skip inactive sources entirely')),
                ('scan_phone_numbers', models.BooleanField(default=False, help_text='Off by default — see model docstring for why this is the one detector worth gating at log scale')),
                ('alert_emails', models.CharField(blank=True, help_text='Comma-separated. One digest email per scan that finds anything, never one email per finding.', max_length=500)),
                ('last_scanned_offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual (on-demand)'), ('scheduled', 'Scheduled'), ('continuous', 'Continuous (tailing)')], default='manual', max_length=10)),
                ('start_offset', models.BigIntegerField(default=0, help_text='Byte offset this job started scanning from')),
                ('bytes_total', models.BigIntegerField(blank=True, help_text='Null when unknown ahead of time (e.g. a growing log)', null=True)),
                ('bytes_scanned', models.BigIntegerField(default=0)),
                ('lines_scanned', models.BigIntegerField(default=0)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='logscan.logsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogPIIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveBigIntegerField()),
                ('byte_offset', models.BigIntegerField()),
                ('pii_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Number'), ('card', 'Credit/Debit Card'), ('iban', 'IBAN'), ('account_number', 'Bank Account Number'), ('address', 'Address')], max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('masked_preview', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='logscan.logscanjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='logscan.logsource')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['source'], name='logscan_log_source__34a588_idx'), models.Index(fields=['job'], name='logscan_log_job_id_4b452d_idx')],
            },
        ),
    ]
