# Generated by Django 6.0.7 on 2026-07-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpiifinding',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='logsource',
            name='file_pattern',
            field=models.CharField(blank=True, default='*.log', help_text="Glob pattern for which files count as logs, e.g. '*.log' or '*.txt'. Directory sources only.", max_length=200),
        ),
        migrations.AddField(
            model_name='logsource',
            name='recursive',
            field=models.BooleanField(default=True, help_text='Include subfolders. Directory sources only.'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='path',
            field=models.CharField(blank=True, help_text="Absolute filesystem or network path — a single file for 'path', a folder for 'directory' (e.g. a mapped NAS share like \\\\fileserver\\logs)", max_length=1000),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='source_type',
            field=models.CharField(choices=[('path', 'Filesystem / network path (single file)'), ('upload', 'Uploaded file'), ('directory', 'Directory / NAS share (many files)')], default='path', max_length=10),
        ),
        migrations.CreateModel(
            name='LogSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1000)),
                ('last_scanned_offset', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Updated every time this file is seen during directory enumeration — a file that stops being seen has likely been deleted/rotated away.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='logscan.logsource')),
            ],
            options={
                'ordering': ['relative_path'],
                'unique_together': {('source', 'relative_path')},
            },
        ),
    ]
