# Generated by Django 6.0.7 on 2026-07-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscan', '0002_logpiifinding_file_path_logsource_file_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPatternCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text="Which file this run analyzed — that source's own filename for path/upload sources", max_length=1000)),
                ('engine', models.CharField(choices=[('traditional_ml', 'Traditional ML')], default='traditional_ml', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('example_line', models.CharField(blank=True, help_text="One representative line from this cluster, normalized and redact_pii()'d before saving — never the raw line", max_length=1000)),
                ('recurring_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_noise', models.BooleanField(default=False, help_text="True for the catch-all 'unclustered' bucket, same convention as clustering.models.Cluster")),
                ('lines_analyzed', models.PositiveIntegerField(default=0, help_text="How many lines this run covered in total — context for recurring_count, e.g. '12 of 4,213 recent lines'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_clusters', to='logscan.logsource')),
            ],
            options={
                'ordering': ['-recurring_count'],
                'indexes': [models.Index(fields=['source', 'file_path'], name='logscan_log_source__ab71af_idx')],
            },
        ),
    ]
