# Generated by Django 6.0.7 on 2026-07-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesettings_embedding_model_path'),
        ('logscan', '0003_logpatterncluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpatterncluster',
            name='first_line_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logpatterncluster',
            name='last_line_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogPatternCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_minutes', models.PositiveIntegerField(default=10)),
                ('overlap_start', models.DateTimeField()),
                ('overlap_end', models.DateTimeField()),
                ('source_count', models.PositiveIntegerField(default=0, help_text='How many distinct LogSources contributed a cluster to this group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_correlations', to='core.project')),
            ],
            options={
                'ordering': ['-overlap_start'],
            },
        ),
        migrations.CreateModel(
            name='LogPatternCorrelationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_memberships', to='logscan.logpatterncluster')),
                ('correlation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='logscan.logpatterncorrelation')),
            ],
            options={
                'unique_together': {('correlation', 'cluster')},
            },
        ),
    ]
