# Generated by Django 6.0.7 on 2026-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscan', '0004_logpatterncluster_first_line_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpatterncluster',
            name='ai_narrative',
            field=models.CharField(blank=True, help_text="Plain-English 'what's likely happening' sentence generated via the Copilot HTTP Bridge (BACKLOG A.6) — same idea as Cluster.ai_summary applied to a log pattern instead of a ticket cluster. Built only from keywords/example_line, both already redacted before saving, so nothing extra to redact here.", max_length=500),
        ),
    ]
