# Generated by Django 6.0.7 on 2026-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscan', '0005_logpatterncluster_ai_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpatterncorrelation',
            name='ai_incident_narrative',
            field=models.CharField(blank=True, help_text="'What happened' story tying this correlation group's member patterns together across sources, generated via the Copilot HTTP Bridge (BACKLOG A.10, user-requested leadership-demo feature) — e.g. 'Auth service degraded, cascading into checkout failures downstream.' Built only from already-redacted example_line/keywords fields, nothing extra to sanitize here.", max_length=1000),
        ),
    ]
