# Generated by Django 6.0.7 on 2026-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logscan', '0006_logpatterncorrelation_ai_incident_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpatterncluster',
            name='ai_narrative',
            field=models.TextField(blank=True, help_text="Plain-English 'what's likely happening' explanation generated via the Copilot HTTP Bridge (BACKLOG A.6) — same idea as Cluster.ai_summary applied to a log pattern instead of a ticket cluster. Built only from keywords/example_line, both already redacted before saving, so nothing extra to redact here. TextField (was CharField(500)) since the prompt now asks for a quote-grounded explanation."),
        ),
        migrations.AlterField(
            model_name='logpatterncorrelation',
            name='ai_incident_narrative',
            field=models.TextField(blank=True, help_text="'What happened' story tying this correlation group's member patterns together across sources, generated via the Copilot HTTP Bridge (BACKLOG A.10, user-requested leadership-demo feature) — e.g. 'Auth service degraded, cascading into checkout failures downstream.' Built only from already-redacted example_line/keywords fields, nothing extra to sanitize here. TextField (was CharField(1000)) since the prompt now asks for a detailed, quote-grounded 4-6 sentence story."),
        ),
    ]
