from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
from django.db import transaction

from clustering.models import Cluster, ClusterMember, DuplicateCandidate, TicketEmbedding
from clustering.scoring import (compute_confidence, compute_problem_thresholds,
                                 compute_trend, is_problem_candidate, most_common,
                                 most_common_multi, recency_fraction)
from clustering.settings_utils import get_or_default as get_clustering_settings
from clustering.text_utils import (build_clustering_text, build_entity_stoplist,
                                    cluster_title, strip_entity_terms, top_keywords)
from tickets.models import Ticket

MIN_TICKETS_TO_CLUSTER = 8

# User-facing granularity control — deliberately NOT raw HDBSCAN parameters exposed
# to the UI. "Broad" is today's original eom/floor-20 behavior (preserved as an
# option, not just a historical default); "Balanced" is the leaf-method fix from the
# under-segmentation story and ships as the default; "Fine-grained" pushes further
# for when a user explicitly wants more, smaller clusters.
GRANULARITY_PRESETS = {
    "broad": {"cluster_selection_method": "eom", "min_cluster_size_floor": 20},
    "balanced": {"cluster_selection_method": "leaf", "min_cluster_size_floor": 15},
    "fine": {"cluster_selection_method": "leaf", "min_cluster_size_floor": 8},
}
DEFAULT_GRANULARITY = "balanced"


class PipelineResult:
    def __init__(self, ran, message, cluster_count=0, noise_count=0):
        self.ran = ran
        self.message = message
        self.cluster_count = cluster_count
        self.noise_count = noise_count


def _min_cluster_size(n, floor=20):
    return int(min(floor, max(3, round(n * 0.03))))


def _compute_cluster_stats(tickets, labels, membership_strength, stoplist,
                            confidence_weight_size=0.40, confidence_weight_density=0.35,
                            confidence_weight_recency=0.25, confidence_recency_window_days=90,
                            confidence_floor=30, confidence_cap=97, settings_for_ticket=None):
    """Per-cluster stats (keywords, confidence, trend, regional breakdown, problem
    thresholds) shared by every persistence path. Operates purely on an arbitrary
    tickets/labels array — never touches a specific project, so the same computation
    backs both single-project Cluster rows and cross-project GlobalCluster rows; only
    the caller decides which model the results get written to.

    The confidence_* parameters default to exactly Project's own model field defaults
    (today's original fixed formula) — _save_clusters passes the actual project's
    configured values; _save_global_clusters (no single project to source them from,
    same reasoning as the vectorizer min_df/max_df precedent) leaves them as these
    fixed defaults.

    `settings_for_ticket(ticket) -> ClusteringSettings|None` drives keyword/cluster-name
    generation through the SAME configurable pipeline (source_fields, remove_numbers,
    stopwords, etc.) that already governs actual clustering — without this, cluster
    names were generated by a completely separate, hardcoded title-only pipeline that
    never stripped numbers regardless of what a project had configured. Stemming is
    always skipped for naming purposes even if enabled for clustering, since a stemmed
    fragment reads worse as a human-facing title than the real word. `None` (the
    default) falls back to the original title-only, no-settings behavior.

    Returns (computed, recurring_threshold, confidence_threshold), where `computed` is
    a list of per-cluster dicts each carrying its own `idx`/`members` for the caller to
    zip back against `coords_3d` when building member rows.
    """
    labels = np.asarray(labels)
    unique_labels = sorted(set(labels.tolist()))
    max_size = max((int((labels == lbl).sum()) for lbl in unique_labels if lbl != -1), default=1)

    computed = []
    for lbl in unique_labels:
        idx = np.where(labels == lbl)[0]
        members = [tickets[i] for i in idx]
        is_noise = lbl == -1

        if settings_for_ticket is not None:
            texts = [build_clustering_text(t, stoplist, settings_for_ticket(t), skip_stemming=True) for t in members]
        else:
            texts = [strip_entity_terms(t.title, stoplist) for t in members]
        keywords = top_keywords(texts, n=5)
        name = "Unclustered / Noise" if is_noise else cluster_title(keywords)

        dates = [t.created_at for t in members]
        avg_strength = float(np.mean([membership_strength[i] for i in idx])) if len(idx) else 0.0
        confidence = 0 if is_noise else compute_confidence(
            cluster_size=len(idx),
            max_cluster_size=max_size,
            avg_membership_strength=avg_strength,
            recency_fraction=recency_fraction(dates, window_days=confidence_recency_window_days),
            weight_size=confidence_weight_size,
            weight_density=confidence_weight_density,
            weight_recency=confidence_weight_recency,
            floor=confidence_floor,
            cap=confidence_cap,
        )
        if is_noise:
            trend, trend_reasoning = "stable", ""
        else:
            trend, trend_reasoning = compute_trend(dates)

        # Regional trend breakdown: a cluster's overall trend is one number that can
        # mask something real (e.g. "stable" overall while actually rising sharply in
        # one country and falling in another). Re-scope the same compute_trend() per
        # country, capped to the top 5 by ticket count — no new statistics, just
        # re-running the existing function on a narrower slice of the same members.
        regional_trends = []
        regional_divergence = False
        if not is_noise:
            country_dates = defaultdict(list)
            for t in members:
                if t.country and t.country != "Unspecified":
                    country_dates[t.country].append(t.created_at)
            top_countries = sorted(country_dates.items(), key=lambda kv: -len(kv[1]))[:5]
            for country, c_dates in top_countries:
                r_trend, r_reasoning = compute_trend(c_dates)
                regional_trends.append({"country": country, "trend": r_trend, "reasoning": r_reasoning, "count": len(c_dates)})
                if r_trend == "rising" and trend != "rising":
                    regional_divergence = True

        computed.append({
            "idx": idx, "members": members, "is_noise": is_noise, "name": name,
            "keywords": keywords, "confidence": confidence, "trend": trend,
            "trend_reasoning": trend_reasoning, "recurring": len(idx),
            "regional_trends": regional_trends, "regional_divergence": regional_divergence,
        })

    recurring_threshold, confidence_threshold = compute_problem_thresholds([
        (c["recurring"], c["confidence"]) for c in computed if not c["is_noise"]
    ])
    return computed, recurring_threshold, confidence_threshold


def _save_clusters(project, engine, tickets, labels, coords_3d, membership_strength, stoplist, source_description, granularity=DEFAULT_GRANULARITY, parent=None):
    """Shared persistence: wipes prior clusters and writes fresh ones.

    Scoped by `parent` when this is a drill-down/sub-cluster run — deleting only
    `Cluster.objects.filter(parent=parent)` rather than the whole project+engine.
    A top-level run (parent=None) keeps the original project+engine scope. Getting
    this wrong would mean a single drill-down silently wipes every other cluster in
    the project on that engine — this scoping is the entire point of threading
    `parent` through in the first place, not incidental.
    """
    if parent is not None:
        Cluster.objects.filter(parent=parent).delete()
    else:
        Cluster.objects.filter(project=project, engine=engine, parent__isnull=True).delete()

    engine_settings = get_clustering_settings(project, engine)
    computed, recurring_threshold, confidence_threshold = _compute_cluster_stats(
        tickets, labels, membership_strength, stoplist,
        confidence_weight_size=project.confidence_weight_size,
        confidence_weight_density=project.confidence_weight_density,
        confidence_weight_recency=project.confidence_weight_recency,
        confidence_recency_window_days=project.confidence_recency_window_days,
        confidence_floor=project.confidence_floor,
        confidence_cap=project.confidence_cap,
        settings_for_ticket=lambda t: engine_settings,
    )

    created_clusters = 0
    noise_count = 0

    with transaction.atomic():
        for c in computed:
            idx, members, is_noise = c["idx"], c["members"], c["is_noise"]

            cluster = Cluster.objects.create(
                project=project,
                engine=engine,
                name=c["name"],
                keywords=", ".join(c["keywords"]),
                confidence=c["confidence"],
                recurring_count=c["recurring"],
                trend=c["trend"],
                trend_reasoning=c["trend_reasoning"],
                is_problem_candidate=False if is_noise else is_problem_candidate(
                    c["recurring"], c["confidence"], c["trend"], recurring_threshold, confidence_threshold
                ),
                is_noise=is_noise,
                top_country=most_common([t.country for t in members]),
                top_application=most_common([t.application for t in members]),
                top_offering=most_common_multi([t.offering_list for t in members]),
                source_description=source_description,
                granularity=granularity,
                regional_trends=c["regional_trends"],
                regional_divergence=c["regional_divergence"],
                parent=parent,
            )

            ClusterMember.objects.bulk_create([
                ClusterMember(
                    cluster=cluster,
                    ticket=tickets[i],
                    similarity=float(membership_strength[i]) * 100,
                    x=float(coords_3d[i][0]),
                    y=float(coords_3d[i][1]),
                    z=float(coords_3d[i][2]) if coords_3d.shape[1] > 2 else 0.0,
                )
                for i in idx
            ])

            if is_noise:
                noise_count = c["recurring"]
            else:
                created_clusters += 1

    return created_clusters, noise_count


def run_traditional_ml(project, ticket_queryset=None, source_description="", granularity=DEFAULT_GRANULARITY, parent=None):
    from sklearn.decomposition import TruncatedSVD
    from sklearn.feature_extraction.text import TfidfVectorizer
    import hdbscan

    preset = GRANULARITY_PRESETS.get(granularity, GRANULARITY_PRESETS[DEFAULT_GRANULARITY])

    tickets = list(ticket_queryset if ticket_queryset is not None else Ticket.objects.filter(project=project))
    if not source_description:
        source_description = f"All {len(tickets)} tickets"
    if len(tickets) < MIN_TICKETS_TO_CLUSTER:
        return PipelineResult(False, f"Need at least {MIN_TICKETS_TO_CLUSTER} tickets to cluster — this selection has {len(tickets)}.")

    cluster_settings = get_clustering_settings(project, "traditional_ml")
    stoplist = build_entity_stoplist(tickets)
    texts = [build_clustering_text(t, stoplist, cluster_settings) for t in tickets]
    # stop_words/lowercase are None/False here since the configurable preprocessing
    # pipeline above already applied them (or deliberately didn't) per cluster_settings
    # — letting the vectorizer also apply its own fixed stopword list or default
    # lowercasing would silently override the user's toggles.
    vectorizer = TfidfVectorizer(
        stop_words=None, lowercase=False, max_features=3000, ngram_range=(1, 2),
        min_df=cluster_settings.min_document_frequency, max_df=cluster_settings.max_document_frequency,
    )
    try:
        tfidf_matrix = vectorizer.fit_transform(texts)
    except ValueError:
        return PipelineResult(False, "Ticket text is too sparse to vectorize (try uploading more descriptive tickets).")

    n_components = min(50, max(2, tfidf_matrix.shape[1] - 1, tfidf_matrix.shape[0] - 1))
    n_components = min(n_components, min(tfidf_matrix.shape) - 1) if min(tfidf_matrix.shape) > 1 else 2
    n_components = max(2, n_components)
    svd = TruncatedSVD(n_components=n_components, random_state=42)
    reduced = svd.fit_transform(tfidf_matrix)

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=_min_cluster_size(len(tickets), preset["min_cluster_size_floor"]),
        metric="euclidean", cluster_selection_method=preset["cluster_selection_method"],
    )
    labels = clusterer.fit_predict(reduced)
    strength = np.nan_to_num(clusterer.probabilities_, nan=0.5)

    coords_3d = _reduce_for_viz(reduced, len(tickets))

    cluster_count, noise_count = _save_clusters(project, "traditional_ml", tickets, labels, coords_3d, strength, stoplist, source_description, granularity, parent)
    return PipelineResult(True, f"Found {cluster_count} clusters ({noise_count} unclustered tickets).", cluster_count, noise_count)


def _reduce_for_viz(feature_matrix, n_samples):
    """Projects a (possibly high-dim) feature space to 3D for visualization only.

    Raw PCA/SVD components maximize variance, not visual cluster separation — UMAP
    (a manifold-learning technique) gives far more legible, separated blobs. This is
    purely cosmetic: it never feeds back into the clustering or confidence scoring.
    """
    try:
        import umap
        reducer = umap.UMAP(
            n_components=3, random_state=42,
            n_neighbors=min(15, max(2, n_samples - 1)),
            min_dist=0.05,  # tighter packing within a cluster = clearer visual separation between clusters
        )
        return reducer.fit_transform(feature_matrix)
    except Exception:
        if feature_matrix.shape[1] >= 3:
            return feature_matrix[:, :3]
        return np.pad(feature_matrix, ((0, 0), (0, 3 - feature_matrix.shape[1])))


_EMBEDDING_MODEL = None
_EMBEDDING_MODEL_PATH = None


class EmbeddingModelUnavailable(Exception):
    """Raised when the configured embedding model path doesn't resolve to a real
    local folder. Deliberately never falls through to a Hugging Face Hub download —
    a misconfigured path fails clearly and immediately (this is what every caller
    below turns into a friendly message) rather than silently attempting a network
    call against huggingface.co for a string that was never meant to be a Hub
    model id, which previously surfaced as an opaque RepositoryNotFoundError."""


def _resolve_model_path(configured_path):
    """A configured path is tried as: a folder relative to the project root (e.g.
    the bundled ./embedding_model), or an absolute local folder. Raises
    EmbeddingModelUnavailable if neither exists — see that class's docstring for why
    there's no Hugging Face Hub fallback."""
    from django.conf import settings

    relative = settings.BASE_DIR / configured_path
    if relative.is_dir():
        return str(relative)
    absolute = Path(configured_path)
    if absolute.is_dir():
        return str(absolute)
    raise EmbeddingModelUnavailable(
        f"No embedding model found at ‘{configured_path}’. Set a valid local "
        "folder path in Clustering Settings (or Admin › Site Settings) before "
        "using Generative AI, Smart Search, Smart Assign, or Possible Duplicates."
    )


def embedding_model_status():
    """Returns (available: bool, message: str) without raising — message is the
    resolved local path if available, or a user-facing explanation if not. Used by
    every view that touches embeddings to guard against attempting the operation at
    all, and by the Clustering Settings page to show a live status indicator."""
    from core.models import SiteSettings
    configured = SiteSettings.load().embedding_model_path or "embedding_model"
    try:
        return True, _resolve_model_path(configured)
    except EmbeddingModelUnavailable as exc:
        return False, str(exc)


def _get_embedding_model():
    """Loads the sentence-embedding model from whatever path is configured in
    Clustering Settings / Admin > Site Settings. Defaults to the ./embedding_model
    folder bundled with this project, so the Generative AI pipeline works with no
    Hugging Face Hub access — when that folder isn't present and nothing else is
    configured, this raises EmbeddingModelUnavailable rather than attempting a
    network call. Callers are expected to check embedding_model_status() first
    (or catch EmbeddingModelUnavailable) rather than let this raise unhandled."""
    global _EMBEDDING_MODEL, _EMBEDDING_MODEL_PATH
    from core.models import SiteSettings
    model_path = _resolve_model_path(SiteSettings.load().embedding_model_path or "embedding_model")
    if _EMBEDDING_MODEL is None or _EMBEDDING_MODEL_PATH != model_path:
        from sentence_transformers import SentenceTransformer
        _EMBEDDING_MODEL = SentenceTransformer(model_path)
        _EMBEDDING_MODEL_PATH = model_path
    return _EMBEDDING_MODEL


def _embed_tickets(tickets, project=None):
    """Embeds tickets' clustering text with the configured embedding model,
    L2-normalized. Shared by the Generative AI pipeline and the standalone search-index
    build — both need the exact same vectors, just for different downstream uses.
    Returns (embeddings, stoplist); stoplist is returned too since callers that go on
    to cluster (not just index) need it for keyword extraction.

    `project` is optional: single-project callers pass it to apply that project's
    Generative AI ClusteringSettings; the cross-project global-clustering pipeline
    passes nothing (there's no single project's settings to apply across a
    multi-project ticket pool), falling back to the pre-feature title-only behavior."""
    from sklearn.preprocessing import normalize

    stoplist = build_entity_stoplist(tickets)
    cluster_settings = get_clustering_settings(project, "generative_ai") if project is not None else None
    texts = [build_clustering_text(t, stoplist, cluster_settings) for t in tickets]
    model = _get_embedding_model()
    embeddings = model.encode(texts, show_progress_bar=False, batch_size=32)
    embeddings = normalize(np.asarray(embeddings))
    return embeddings, stoplist


def _persist_embeddings(project, tickets, embeddings):
    """Upserts a TicketEmbedding row per ticket using vectors already computed by
    `_embed_tickets` — no extra embedding pass. Scoped delete-then-recreate by the
    tickets actually passed in, NOT by project — a partial/scoped run (e.g. one
    upload batch) must never wipe the rest of the project's search index. Stale rows
    for tickets that get deleted entirely are cleaned up for free via the
    OneToOneField's CASCADE, so no separate stale-cleanup pass is needed here."""
    from core.models import SiteSettings

    if not tickets:
        return
    model_path = _resolve_model_path(SiteSettings.load().embedding_model_path or "embedding_model")
    dims = int(embeddings.shape[1])
    ticket_ids = [t.id for t in tickets]
    with transaction.atomic():
        TicketEmbedding.objects.filter(ticket_id__in=ticket_ids).delete()
        TicketEmbedding.objects.bulk_create([
            TicketEmbedding(
                ticket=ticket,
                project=project,
                vector=np.asarray(vector, dtype=np.float32).tobytes(),
                dims=dims,
                model_path=model_path,
            )
            for ticket, vector in zip(tickets, embeddings)
        ])


def build_search_index(project, ticket_queryset=None):
    """Embeds and persists TicketEmbedding rows without running clustering — for
    projects that have only ever used Traditional ML, or to refresh the index for
    tickets uploaded since the last Generative AI run, without forcing a full
    re-cluster."""
    tickets = list(ticket_queryset if ticket_queryset is not None else Ticket.objects.filter(project=project))
    if not tickets:
        return PipelineResult(False, "No tickets to index.")
    try:
        embeddings, _ = _embed_tickets(tickets, project)
    except EmbeddingModelUnavailable as exc:
        return PipelineResult(False, str(exc))
    _persist_embeddings(project, tickets, embeddings)
    return PipelineResult(True, f"Indexed {len(tickets)} tickets for search.")


DUPLICATE_SIMILARITY_THRESHOLD = 0.92  # high bar deliberately — this flags likely
# duplicates, not "same topic" (that's what clustering is for)
DUPLICATE_TIME_WINDOW_DAYS = 7


def scan_for_duplicates(project):
    """Pairwise-compares every embedded ticket in the project and creates
    DuplicateCandidate rows for pairs that are BOTH highly similar AND credible as an
    actual duplicate (close in time, and reported by the same person or against the
    same application) — high embedding similarity alone just means "same topic,"
    which is what Cluster already covers; these two extra signals are what turn a
    topical match into an actual duplicate claim.

    The O(n^2) similarity matrix itself is one vectorized numpy matmul (fast even at
    thousands of tickets); only the post-filtering narrowing loops over pairs that
    already cleared the high similarity bar, which is normally a small fraction of
    all pairs — not a loop over every pair.
    """
    rows = list(TicketEmbedding.objects.filter(project=project).select_related("ticket"))
    n = len(rows)
    if n < 2:
        return 0

    matrix = np.vstack([np.frombuffer(r.vector, dtype=np.float32) for r in rows])
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    matrix = matrix / np.where(norms == 0, 1.0, norms)
    sim = matrix @ matrix.T

    upper_i, upper_j = np.triu_indices(n, k=1)
    pair_sims = sim[upper_i, upper_j]
    above_threshold = pair_sims >= DUPLICATE_SIMILARITY_THRESHOLD
    candidate_i = upper_i[above_threshold]
    candidate_j = upper_j[above_threshold]
    candidate_sims = pair_sims[above_threshold]

    tickets = [r.ticket for r in rows]
    existing_pairs = set(
        DuplicateCandidate.objects.filter(ticket_a__project=project).values_list("ticket_a_id", "ticket_b_id")
    )

    to_create = []
    for i, j, sim_score in zip(candidate_i, candidate_j, candidate_sims):
        t1, t2 = tickets[i], tickets[j]
        time_gap_days = abs(t1.created_at - t2.created_at).days
        if time_gap_days > DUPLICATE_TIME_WINDOW_DAYS:
            continue
        same_reporter = t1.created_by == t2.created_by and t1.created_by != "Unknown"
        same_app = t1.application == t2.application and t1.application != "Unspecified"
        if not (same_reporter or same_app):
            continue
        a_id, b_id = sorted([t1.id, t2.id])
        if (a_id, b_id) in existing_pairs:
            continue
        existing_pairs.add((a_id, b_id))
        to_create.append(DuplicateCandidate(ticket_a_id=a_id, ticket_b_id=b_id, similarity=float(sim_score) * 100))

    with transaction.atomic():
        DuplicateCandidate.objects.bulk_create(to_create)
    return len(to_create)


def run_generative_ai(project, ticket_queryset=None, source_description="", granularity=DEFAULT_GRANULARITY, parent=None):
    import hdbscan

    preset = GRANULARITY_PRESETS.get(granularity, GRANULARITY_PRESETS[DEFAULT_GRANULARITY])

    tickets = list(ticket_queryset if ticket_queryset is not None else Ticket.objects.filter(project=project))
    if not source_description:
        source_description = f"All {len(tickets)} tickets"
    if len(tickets) < MIN_TICKETS_TO_CLUSTER:
        return PipelineResult(False, f"Need at least {MIN_TICKETS_TO_CLUSTER} tickets to cluster — this selection has {len(tickets)}.")

    try:
        embeddings, stoplist = _embed_tickets(tickets, project)
    except EmbeddingModelUnavailable as exc:
        return PipelineResult(False, str(exc))
    _persist_embeddings(project, tickets, embeddings)

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=_min_cluster_size(len(tickets), preset["min_cluster_size_floor"]),
        metric="euclidean", cluster_selection_method=preset["cluster_selection_method"],
    )
    labels = clusterer.fit_predict(embeddings)
    strength = np.nan_to_num(clusterer.probabilities_, nan=0.5)

    coords_3d = _reduce_for_viz(embeddings, len(tickets))

    cluster_count, noise_count = _save_clusters(project, "generative_ai", tickets, labels, coords_3d, strength, stoplist, source_description, granularity, parent)
    return PipelineResult(True, f"Found {cluster_count} semantic clusters ({noise_count} unclustered tickets).", cluster_count, noise_count)


def _is_significant_intersection(project_counter):
    """A cluster with tickets from 2+ projects isn't automatically a credible
    cross-project intersection — a single stray ticket landing in an otherwise
    single-project cluster of 70+ is far more likely coincidence than a shared
    incident. Requires the non-majority project(s) to contribute at least 3
    tickets AND at least 10% of the cluster before it earns that label."""
    if len(project_counter) < 2:
        return False
    counts = sorted(project_counter.values(), reverse=True)
    minority_total = sum(counts[1:])
    cluster_total = sum(counts)
    return minority_total >= 3 and minority_total >= 0.10 * cluster_total


def _save_global_clusters(engine, tickets, labels, coords_3d, membership_strength, stoplist, granularity, source_description, run_by=None, settings_for_ticket=None):
    """GlobalCluster's equivalent of _save_clusters — same wipe-then-recreate
    convention, scoped by engine only since a global run has no single project to
    scope by. Reuses the exact same per-cluster stats computation as the per-project
    path (_compute_cluster_stats); the only genuinely new thing here is project_count,
    which is what turns "a cluster" into "a cross-project intersection worth flagging."

    `settings_for_ticket` (same per-ticket-project cache the caller already built for
    text/embedding generation) drives keyword/cluster-name generation too, for the
    same reason it drives the actual clustering — see Epic 6.1's design note.
    """
    from clustering.models import GlobalCluster, GlobalClusterMember

    GlobalCluster.objects.filter(engine=engine, run_by=run_by).delete()

    computed, recurring_threshold, confidence_threshold = _compute_cluster_stats(
        tickets, labels, membership_strength, stoplist, settings_for_ticket=settings_for_ticket
    )

    created_clusters = 0
    noise_count = 0
    intersection_count = 0

    with transaction.atomic():
        for c in computed:
            idx, members, is_noise = c["idx"], c["members"], c["is_noise"]
            project_counter = Counter(t.project_id for t in members)
            project_ids = set(project_counter)
            significant = _is_significant_intersection(project_counter)

            cluster = GlobalCluster.objects.create(
                engine=engine,
                name=c["name"],
                keywords=", ".join(c["keywords"]),
                confidence=c["confidence"],
                recurring_count=c["recurring"],
                trend=c["trend"],
                trend_reasoning=c["trend_reasoning"],
                is_noise=is_noise,
                top_country=most_common([t.country for t in members]),
                top_application=most_common([t.application for t in members]),
                top_offering=most_common_multi([t.offering_list for t in members]),
                granularity=granularity,
                source_description=source_description,
                project_count=len(project_ids),
                is_significant_intersection=significant,
                run_by=run_by,
            )

            GlobalClusterMember.objects.bulk_create([
                GlobalClusterMember(
                    cluster=cluster,
                    ticket=tickets[i],
                    project_id=tickets[i].project_id,
                    similarity=float(membership_strength[i]) * 100,
                    x=float(coords_3d[i][0]),
                    y=float(coords_3d[i][1]),
                    z=float(coords_3d[i][2]) if coords_3d.shape[1] > 2 else 0.0,
                )
                for i in idx
            ])

            if is_noise:
                noise_count = c["recurring"]
            else:
                created_clusters += 1
                if significant:
                    intersection_count += 1

    return created_clusters, noise_count, intersection_count


def run_global_clustering(engine, project_ids=None, granularity=DEFAULT_GRANULARITY, run_by=None):
    """Cross-project clustering for the "how does this look across everything my team
    has uploaded" report. Same two engines as the per-project pipelines, same
    granularity presets — the only difference is the ticket pool spans however many
    projects were selected instead of exactly one. Deliberately does NOT reuse
    run_traditional_ml/run_generative_ai (both hard-require a single `project` and
    write straight to Cluster) — small, acceptable duplication of the vectorize/
    cluster steps here keeps the well-tested single-project pipelines completely
    unchanged, in exchange for ~20 duplicated lines per engine.
    """
    qs = Ticket.objects.filter(project_id__in=project_ids) if project_ids else Ticket.objects.all()
    tickets = list(qs.select_related("project"))
    included_project_count = len({t.project_id for t in tickets})
    source_description = f"Global run across {included_project_count} project{'s' if included_project_count != 1 else ''}, {len(tickets)} tickets"

    if len(tickets) < MIN_TICKETS_TO_CLUSTER:
        return PipelineResult(False, f"Need at least {MIN_TICKETS_TO_CLUSTER} tickets across the selected projects to cluster — this selection has {len(tickets)}.")

    preset = GRANULARITY_PRESETS.get(granularity, GRANULARITY_PRESETS[DEFAULT_GRANULARITY])

    # Every ticket in a global run still belongs to exactly one project — apply that
    # project's own ClusteringSettings to its text, cached per project_id so a run
    # spanning many tickets from a handful of projects only looks each one up once.
    # Vectorizer-level tuning (min_df/max_df below) stays a fixed global-run constant
    # regardless — it's a statistic over the *combined* cross-project corpus, and no
    # single project's setting can meaningfully represent that.
    settings_cache = {}

    def _settings_for(ticket):
        if ticket.project_id not in settings_cache:
            settings_cache[ticket.project_id] = get_clustering_settings(ticket.project, engine)
        return settings_cache[ticket.project_id]

    if engine == "traditional_ml":
        from sklearn.decomposition import TruncatedSVD
        from sklearn.feature_extraction.text import TfidfVectorizer
        import hdbscan

        stoplist = build_entity_stoplist(tickets)
        texts = [build_clustering_text(t, stoplist, _settings_for(t)) for t in tickets]
        # stop_words/lowercase off — each ticket's own project settings already applied
        # (or deliberately didn't apply) those, same reasoning as run_traditional_ml.
        vectorizer = TfidfVectorizer(stop_words=None, lowercase=False, max_features=3000, ngram_range=(1, 2), min_df=2, max_df=0.6)
        try:
            tfidf_matrix = vectorizer.fit_transform(texts)
        except ValueError:
            return PipelineResult(False, "Ticket text across the selected projects is too sparse to vectorize.")

        n_components = min(50, max(2, tfidf_matrix.shape[1] - 1, tfidf_matrix.shape[0] - 1))
        n_components = min(n_components, min(tfidf_matrix.shape) - 1) if min(tfidf_matrix.shape) > 1 else 2
        n_components = max(2, n_components)
        reduced = TruncatedSVD(n_components=n_components, random_state=42).fit_transform(tfidf_matrix)

        clusterer = hdbscan.HDBSCAN(
            min_cluster_size=_min_cluster_size(len(tickets), preset["min_cluster_size_floor"]),
            metric="euclidean", cluster_selection_method=preset["cluster_selection_method"],
        )
        labels = clusterer.fit_predict(reduced)
        strength = np.nan_to_num(clusterer.probabilities_, nan=0.5)
        coords_3d = _reduce_for_viz(reduced, len(tickets))

    elif engine == "generative_ai":
        from sklearn.preprocessing import normalize
        import hdbscan

        stoplist = build_entity_stoplist(tickets)
        texts = [build_clustering_text(t, stoplist, _settings_for(t)) for t in tickets]
        try:
            model = _get_embedding_model()
        except EmbeddingModelUnavailable as exc:
            return PipelineResult(False, str(exc))
        embeddings = model.encode(texts, show_progress_bar=False, batch_size=32)
        embeddings = normalize(np.asarray(embeddings))

        clusterer = hdbscan.HDBSCAN(
            min_cluster_size=_min_cluster_size(len(tickets), preset["min_cluster_size_floor"]),
            metric="euclidean", cluster_selection_method=preset["cluster_selection_method"],
        )
        labels = clusterer.fit_predict(embeddings)
        strength = np.nan_to_num(clusterer.probabilities_, nan=0.5)
        coords_3d = _reduce_for_viz(embeddings, len(tickets))

    else:
        return PipelineResult(False, f"Unknown engine '{engine}'.")

    cluster_count, noise_count, intersection_count = _save_global_clusters(engine, tickets, labels, coords_3d, strength, stoplist, granularity, source_description, run_by, settings_for_ticket=_settings_for)
    intersection_note = f", {intersection_count} spanning multiple projects" if intersection_count else ""
    return PipelineResult(True, f"Found {cluster_count} clusters across {included_project_count} project{'s' if included_project_count != 1 else ''}{intersection_note} ({noise_count} unclustered tickets).", cluster_count, noise_count)
