# Generated by Django 6.0.7 on 2026-07-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded — awaiting column mapping'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('datetime_format', models.CharField(default='auto', max_length=40)),
                ('detected_columns', models.JSONField(blank=True, default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('country', models.CharField(blank=True, default='Unspecified', max_length=100)),
                ('application', models.CharField(blank=True, default='Unspecified', max_length=150)),
                ('status', models.CharField(blank=True, default='Open', max_length=50)),
                ('priority', models.CharField(blank=True, default='Medium', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.project')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.uploadbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='tickets_tic_project_de1ed1_idx'), models.Index(fields=['project', 'country'], name='tickets_tic_project_dd5fb4_idx'), models.Index(fields=['project', 'application'], name='tickets_tic_project_0bf91b_idx')],
            },
        ),
    ]
