# Generated by Django 6.0.7 on 2026-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='warning_log',
            field=models.JSONField(blank=True, default=list, help_text='Rows imported using an auto-generated fallback for an unmapped/unparseable field'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='error_log',
            field=models.JSONField(blank=True, default=list, help_text='Rows that were skipped entirely (e.g. duplicate ID)'),
        ),
    ]
