# Generated by Django 6.0.7 on 2026-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_uploadbatch_warning_log_alter_uploadbatch_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text="Sequential upload number within this project — resets when the project's data is reset"),
        ),
    ]
