# Generated by Django 6.0.7 on 2026-07-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
        ('tickets', '0003_uploadbatch_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, default='Unassigned', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(blank=True, default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='offering',
            field=models.CharField(blank=True, default='Unspecified', help_text='Raw value from the source column — may contain multiple offerings delimited by , ; | /', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requested_type',
            field=models.CharField(blank=True, default='Unspecified', max_length=100),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'offering'], name='tickets_tic_project_3fd0dc_idx'),
        ),
    ]
