# Generated by Django 6.0.7 on 2026-07-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_assigned_to_ticket_created_by_ticket_offering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.CharField(blank=True, default='Unspecified', help_text='Assignment group / team queue — distinct from application or offering', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue_source',
            field=models.CharField(blank=True, choices=[('mapped', 'From source column'), ('suggested', 'AI-suggested, accepted')], default='', help_text='How the current queue value was set — blank if queue is still Unspecified', max_length=20),
        ),
    ]
