# Generated by Django 6.0.7 on 2026-07-16 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesettings_embedding_model_path'),
        ('tickets', '0005_ticket_queue_ticket_queue_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=150)),
                ('row_reference', models.CharField(blank=True, max_length=100)),
                ('pii_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Number'), ('card', 'Credit/Debit Card'), ('iban', 'IBAN'), ('account_number', 'Bank Account Number'), ('address', 'Address')], max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('masked_preview', models.CharField(help_text='e.g. j***@***.com — never the raw value', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_findings', to='core.project')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_findings', to='tickets.ticket')),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_findings', to='tickets.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['upload_batch'], name='tickets_pii_upload__d63074_idx'), models.Index(fields=['project'], name='tickets_pii_project_94646e_idx')],
            },
        ),
    ]
