# Generated by Django 6.0.7 on 2026-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_piifinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='piifinding',
            name='context',
            field=models.CharField(choices=[('identity_field', 'Expected Identity Field'), ('unmapped_column', 'Unmapped Column'), ('free_text', 'Free-Text Field')], default='free_text', help_text="Whether this finding is in a column expected to hold an identity (created_by/assigned_to — not a surprise), an unmapped column (data nobody chose to import), or an ordinary mapped free-text field. Used to surface unmapped_column/free_text findings first, since a name/email in an identity column isn't a leak.", max_length=20),
        ),
    ]
